// GENERATED by tool/generate_catalog.dart — DO NOT EDIT.
// Source: data/ingredient_catalog.json
part of 'bad_ingredients.dart';

const List<IngredientEntry> badIngredientCatalog = [
  IngredientEntry(
    canonicalKey: 'aspartame',
    reasonCode: 'artificial_sweetener',
    aliases: ['아스파탐', 'aspartame', 'E951'],
  ),
  IngredientEntry(
    canonicalKey: 'sucralose',
    reasonCode: 'artificial_sweetener',
    aliases: ['수크랄로스', 'sucralose', 'E955'],
  ),
  IngredientEntry(
    canonicalKey: 'acesulfame_k',
    reasonCode: 'artificial_sweetener',
    aliases: ['아세설팜칼륨', 'acesulfame', 'ace-k', 'acesulfame potassium', 'E950'],
  ),
  IngredientEntry(
    canonicalKey: 'saccharin',
    reasonCode: 'artificial_sweetener',
    aliases: ['사카린', 'saccharin', 'E954'],
  ),
  IngredientEntry(
    canonicalKey: 'red_40',
    reasonCode: 'artificial_color',
    aliases: ['적색40호', '적색 40호', 'red 40', 'allura red', 'E129', '식용색소적색제40호'],
  ),
  IngredientEntry(
    canonicalKey: 'yellow_5',
    reasonCode: 'artificial_color',
    aliases: ['황색5호', '황색 5호', 'yellow 5', 'tartrazine', 'E102', '황색제4호'],
  ),
  IngredientEntry(
    canonicalKey: 'yellow_6',
    reasonCode: 'artificial_color',
    aliases: ['황색6호', '황색 6호', 'yellow 6', 'sunset yellow', 'E110', '황색제5호'],
  ),
  IngredientEntry(
    canonicalKey: 'blue_1',
    reasonCode: 'artificial_color',
    aliases: ['청색1호', '청색 1호', 'blue 1', 'brilliant blue', 'E133', '청색제1호'],
  ),
  IngredientEntry(
    canonicalKey: 'red_3',
    reasonCode: 'artificial_color',
    aliases: ['적색3호', '적색 3호', 'red 3', 'erythrosine', 'E127', '적색제3호'],
  ),
  IngredientEntry(
    canonicalKey: 'hfcs',
    reasonCode: 'hfcs',
    aliases: [
      '고과당옥수수시럽',
      '액상과당',
      '과당시럽',
      '콘시럽',
      'high fructose corn syrup',
      'hfcs',
      'corn syrup',
      '이성화당',
    ],
  ),
  IngredientEntry(
    canonicalKey: 'soybean_oil',
    reasonCode: 'seed_oil',
    aliases: ['대두유', '콩기름', '대두기름', 'soybean oil'],
  ),
  IngredientEntry(
    canonicalKey: 'canola_oil',
    reasonCode: 'seed_oil',
    aliases: ['카놀라유', '채종유', 'canola oil', 'rapeseed oil'],
  ),
  IngredientEntry(
    canonicalKey: 'corn_oil',
    reasonCode: 'seed_oil',
    aliases: ['옥수수유', '옥수수기름', 'corn oil'],
  ),
  IngredientEntry(
    canonicalKey: 'sunflower_oil_refined',
    reasonCode: 'seed_oil',
    aliases: ['정제 해바라기씨유', '정제해바라기씨유', 'refined sunflower oil'],
  ),
  IngredientEntry(
    canonicalKey: 'cottonseed_oil',
    reasonCode: 'seed_oil',
    aliases: ['면실유', 'cottonseed oil', '목화씨앗유', '목화씨유'],
  ),
  IngredientEntry(
    canonicalKey: 'hydrogenated',
    reasonCode: 'hydrogenated_oil',
    aliases: [
      '경화유',
      '부분경화유',
      '부분 경화유',
      'hydrogenated',
      'partially hydrogenated',
      '트랜스지방',
      '경화코코넛오일',
      '경화코코넛유',
      '경화팜핵유',
    ],
  ),
  IngredientEntry(
    canonicalKey: 'bha',
    reasonCode: 'synthetic_preservative',
    aliases: ['bha', '부틸하이드록시아니솔', 'butylated hydroxyanisole', 'E320'],
  ),
  IngredientEntry(
    canonicalKey: 'bht',
    reasonCode: 'synthetic_preservative',
    aliases: ['bht', '부틸하이드록시톨루엔', 'butylated hydroxytoluene', 'E321'],
  ),
  IngredientEntry(
    canonicalKey: 'tbhq',
    reasonCode: 'synthetic_preservative',
    aliases: ['tbhq', '터셔리부틸하이드로퀴논', 'tert-butylhydroquinone', 'E319'],
  ),
  IngredientEntry(
    canonicalKey: 'sodium_nitrite',
    reasonCode: 'nitrite',
    aliases: ['아질산나트륨', 'sodium nitrite', 'E250'],
  ),
  IngredientEntry(
    canonicalKey: 'sodium_nitrate',
    reasonCode: 'nitrite',
    aliases: ['sodium nitrate', 'E251'],
  ),
  IngredientEntry(
    canonicalKey: 'carrageenan',
    reasonCode: 'carrageenan',
    aliases: ['카라기난', 'carrageenan', 'E407'],
  ),
  IngredientEntry(
    canonicalKey: 'polysorbate_80',
    reasonCode: 'emulsifier_concern',
    aliases: ['폴리소르베이트80', '폴리소르베이트 80', 'polysorbate 80', 'E433'],
  ),
  IngredientEntry(
    canonicalKey: 'datem',
    reasonCode: 'emulsifier_concern',
    aliases: ['datem', '다템', '글리세린디아세틸주석산지방산에스테르'],
  ),
  IngredientEntry(
    canonicalKey: 'mono_diglycerides',
    reasonCode: 'emulsifier_concern',
    aliases: [
      '모노글리세리드',
      '디글리세리드',
      'mono- and diglycerides',
      'monoglycerides',
      'diglycerides',
      'E471',
    ],
  ),
  IngredientEntry(
    canonicalKey: 'natural_flavors_opaque',
    reasonCode: 'opaque_flavor',
    aliases: ['natural flavors', '천연향료'],
  ),
  IngredientEntry(
    canonicalKey: 'artificial_flavors',
    reasonCode: 'opaque_flavor',
    aliases: ['합성착향료', '인공향료', 'artificial flavors', 'artificial flavor'],
  ),
  IngredientEntry(
    canonicalKey: 'bleached_flour',
    reasonCode: 'refined_flour',
    aliases: ['표백 밀가루', '표백밀가루', 'bleached flour'],
  ),
  IngredientEntry(
    canonicalKey: 'enriched_flour',
    reasonCode: 'refined_flour',
    aliases: ['강화 밀가루', '강화밀가루', 'enriched flour'],
  ),
  IngredientEntry(
    canonicalKey: 'potassium_bromate',
    reasonCode: 'bromate',
    aliases: ['브롬산칼륨', 'potassium bromate', 'E924'],
  ),
  IngredientEntry(
    canonicalKey: 'maltodextrin',
    reasonCode: 'maltodextrin',
    aliases: ['말토덱스트린', 'maltodextrin', 'E1400'],
  ),
  IngredientEntry(
    canonicalKey: 'sugar',
    reasonCode: 'refined_sugar',
    aliases: ['설탕'],
  ),
];
