// GENERATED by tool/generate_catalog.dart — DO NOT EDIT.
// Source: data/ingredient_catalog.json
part of 'good_ingredients.dart';

const List<IngredientEntry> goodIngredientCatalog = [
  IngredientEntry(
    canonicalKey: 'extra_virgin_olive_oil',
    reasonCode: 'clean_fat',
    aliases: ['엑스트라버진 올리브유', '엑스트라 버진 올리브유', 'evoo', 'extra virgin olive oil'],
  ),
  IngredientEntry(
    canonicalKey: 'avocado_oil',
    reasonCode: 'clean_fat',
    aliases: ['아보카도 오일', '아보카도오일', 'avocado oil'],
  ),
  IngredientEntry(
    canonicalKey: 'coconut_oil',
    reasonCode: 'clean_fat',
    aliases: ['코코넛 오일', '코코넛오일', 'coconut oil'],
  ),
  IngredientEntry(
    canonicalKey: 'grass_fed_butter',
    reasonCode: 'clean_fat',
    aliases: [
      '그래스페드 버터',
      '그래스 페드 버터',
      'grass-fed butter',
      'grass fed butter',
      '기 버터',
      'ghee',
    ],
  ),
  IngredientEntry(
    canonicalKey: 'honey',
    reasonCode: 'natural_sweetener',
    aliases: ['꿀', 'honey'],
  ),
  IngredientEntry(
    canonicalKey: 'maple_syrup',
    reasonCode: 'natural_sweetener',
    aliases: ['메이플시럽', '메이플 시럽', 'maple syrup'],
  ),
  IngredientEntry(
    canonicalKey: 'date',
    reasonCode: 'natural_sweetener',
    aliases: ['대추야자', 'dates', 'medjool'],
  ),
  IngredientEntry(
    canonicalKey: 'sea_salt',
    reasonCode: 'natural_salt',
    aliases: ['천일염', 'sea salt'],
  ),
  IngredientEntry(
    canonicalKey: 'whole_grain',
    reasonCode: 'whole_grain',
    aliases: ['통곡물', '통밀', 'whole grain', 'whole wheat'],
  ),
  IngredientEntry(
    canonicalKey: 'sprouted_grain',
    reasonCode: 'whole_grain',
    aliases: ['발아곡물', 'sprouted grain', 'sprouted wheat'],
  ),
  IngredientEntry(
    canonicalKey: 'kimchi',
    reasonCode: 'fermented',
    aliases: ['김치', 'kimchi'],
  ),
  IngredientEntry(
    canonicalKey: 'kefir',
    reasonCode: 'fermented',
    aliases: ['케피어', 'kefir'],
  ),
  IngredientEntry(
    canonicalKey: 'sauerkraut',
    reasonCode: 'fermented',
    aliases: ['사우어크라우트', 'sauerkraut'],
  ),
  IngredientEntry(
    canonicalKey: 'kombucha',
    reasonCode: 'fermented',
    aliases: ['콤부차', 'kombucha'],
  ),
  IngredientEntry(
    canonicalKey: 'organic',
    reasonCode: 'organic',
    aliases: ['유기농', 'organic'],
  ),
  IngredientEntry(
    canonicalKey: 'pasture_raised_egg',
    reasonCode: 'pasture_raised',
    aliases: [
      '방목 달걀',
      '방목달걀',
      'pasture-raised egg',
      'pasture raised egg',
      'free-range egg',
    ],
  ),
  IngredientEntry(
    canonicalKey: 'grass_fed_beef',
    reasonCode: 'grass_fed',
    aliases: ['그래스페드 소고기', 'grass-fed beef', 'grass fed beef'],
  ),
];
