/// `data/ingredient_catalog.json` (JSON 진실원) → `lib/src/bad_ingredients.g.dart`,
/// `lib/src/good_ingredients.g.dart` (part 파일) 생성 스크립트.
///
/// `dart run tool/generate_catalog.dart` (패키지 루트에서 실행).
library;

import 'dart:convert';
import 'dart:io';

/// bad 측 reasonCode 허용값 (`BadReasonCode`와 동일 — lib/src/bad_ingredients.dart 참조).
const _badReasonCodes = {
  'artificial_sweetener',
  'artificial_color',
  'hfcs',
  'seed_oil',
  'hydrogenated_oil',
  'synthetic_preservative',
  'nitrite',
  'carrageenan',
  'emulsifier_concern',
  'opaque_flavor',
  'refined_flour',
  'bromate',
  'maltodextrin',
  'refined_sugar',
};

/// good 측 reasonCode 허용값 (`GoodReasonCode`와 동일 — lib/src/good_ingredients.dart 참조).
const _goodReasonCodes = {
  'clean_fat',
  'natural_sweetener',
  'natural_salt',
  'whole_food',
  'organic',
  'fermented',
  'whole_grain',
  'pasture_raised',
  'grass_fed',
};

void main() {
  final inputFile = File.fromUri(
    Platform.script.resolve('../data/ingredient_catalog.json'),
  );
  final badOutputFile = File.fromUri(
    Platform.script.resolve('../lib/src/bad_ingredients.g.dart'),
  );
  final goodOutputFile = File.fromUri(
    Platform.script.resolve('../lib/src/good_ingredients.g.dart'),
  );

  final decoded = jsonDecode(inputFile.readAsStringSync());
  if (decoded is! Map<String, Object?>) {
    _fail('${inputFile.path}: top-level JSON은 object여야 합니다.');
  }
  final root = decoded;

  if (root['schemaVersion'] != 1) {
    _fail('schemaVersion 은 1 이어야 합니다 (실제: ${root['schemaVersion']}).');
  }

  final badJson = root['bad'];
  final goodJson = root['good'];
  if (badJson is! List) _fail('"bad" 는 리스트여야 합니다.');
  if (goodJson is! List) _fail('"good" 는 리스트여야 합니다.');

  final seenKeys = <String>{};
  final badEntries = _validateEntries(
    badJson,
    label: 'bad',
    allowedReasonCodes: _badReasonCodes,
    seenKeys: seenKeys,
  );
  final goodEntries = _validateEntries(
    goodJson,
    label: 'good',
    allowedReasonCodes: _goodReasonCodes,
    seenKeys: seenKeys,
  );

  _writePart(
    file: badOutputFile,
    partOfFileName: 'bad_ingredients.dart',
    catalogName: 'badIngredientCatalog',
    entries: badEntries,
  );
  _writePart(
    file: goodOutputFile,
    partOfFileName: 'good_ingredients.dart',
    catalogName: 'goodIngredientCatalog',
    entries: goodEntries,
  );

  final format = Process.runSync('dart', [
    'format',
    badOutputFile.path,
    goodOutputFile.path,
  ]);
  if (format.exitCode != 0) {
    _fail('dart format 실패:\n${format.stdout}\n${format.stderr}');
  }

  stdout.writeln(
    'Generated bad=${badEntries.length}, good=${goodEntries.length}',
  );
}

class _Entry {
  final String canonicalKey;
  final String reasonCode;
  final List<String> aliases;

  _Entry({
    required this.canonicalKey,
    required this.reasonCode,
    required this.aliases,
  });
}

List<_Entry> _validateEntries(
  List<Object?> raw, {
  required String label,
  required Set<String> allowedReasonCodes,
  required Set<String> seenKeys,
}) {
  final entries = <_Entry>[];
  for (final item in raw) {
    if (item is! Map<String, Object?>) {
      _fail('"$label" 엔트리는 object여야 합니다: $item');
    }
    final map = item;

    final canonicalKey = map['canonicalKey'];
    if (canonicalKey is! String || canonicalKey.isEmpty) {
      _fail('"$label" 엔트리의 canonicalKey가 비지 않은 문자열이 아닙니다: $map');
    }
    if (!seenKeys.add(canonicalKey)) {
      _fail('중복된 canonicalKey: "$canonicalKey" ($map)');
    }

    final reasonCode = map['reasonCode'];
    if (reasonCode is! String || !allowedReasonCodes.contains(reasonCode)) {
      _fail(
        '"$label" 엔트리 "$canonicalKey"의 reasonCode가 허용집합에 없습니다: $reasonCode',
      );
    }

    final aliasesRaw = map['aliases'];
    if (aliasesRaw is! List || aliasesRaw.isEmpty) {
      _fail(
        '"$label" 엔트리 "$canonicalKey"의 aliases가 비지 않은 리스트가 아닙니다: $aliasesRaw',
      );
    }
    final aliases = <String>[];
    for (final alias in aliasesRaw) {
      if (alias is! String || alias.isEmpty) {
        _fail('"$label" 엔트리 "$canonicalKey"의 alias가 비지 않은 문자열이 아닙니다: $alias');
      }
      aliases.add(alias);
    }

    entries.add(
      _Entry(
        canonicalKey: canonicalKey,
        reasonCode: reasonCode,
        aliases: aliases,
      ),
    );
  }
  return entries;
}

void _writePart({
  required File file,
  required String partOfFileName,
  required String catalogName,
  required List<_Entry> entries,
}) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/generate_catalog.dart — DO NOT EDIT.')
    ..writeln('// Source: data/ingredient_catalog.json')
    ..writeln("part of '$partOfFileName';")
    ..writeln()
    ..writeln('const List<IngredientEntry> $catalogName = [');
  for (final entry in entries) {
    buffer
      ..writeln('  IngredientEntry(')
      ..writeln('    canonicalKey: ${_quote(entry.canonicalKey)},')
      ..writeln('    reasonCode: ${_quote(entry.reasonCode)},')
      ..writeln('    aliases: [${entry.aliases.map(_quote).join(', ')}],')
      ..writeln('  ),');
  }
  buffer.writeln('];');

  file.writeAsStringSync(buffer.toString());
}

/// 작은따옴표 문자열 리터럴로 방출 — 내부 작은따옴표·역슬래시는 방어적으로 이스케이프.
String _quote(String value) {
  final escaped = value.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
  return "'$escaped'";
}

Never _fail(String message) {
  stderr.writeln(message);
  exit(1);
}
