/// HappyCart MVP seed generator.
///
/// JSON fixture 를 읽고 각 제품의 원재료 토큰 리스트를 `happycart_rules` 에
/// 통과시켜 verdict / bad / good / reason codes 를 산출한 뒤, 시드용
/// SQL migration 본문을 stdout 으로 출력한다.
///
/// 사용:
///   cd happycart
///   dart run --verbosity=error tool/compute_verdicts.dart
///   dart run --verbosity=error tool/compute_verdicts.dart path/to/fixture.json
///   dart run --verbosity=error tool/compute_verdicts.dart \
///     > ../supabase/migrations/0005_seed_products.sql
///
/// 재실행 시 동일 fixture (특히 `fixed_computed_at`) 이면 byte-identical 출력 —
/// migration idempotency 유지.
library;

import 'dart:convert';
import 'dart:io';

import 'package:happycart_rules/happycart_rules.dart';

const _defaultFixturePath = 'tool/fixtures/seed_products.json';

void main(List<String> args) {
  final fixturePath = args.isEmpty ? _defaultFixturePath : args.first;
  final file = File(fixturePath);
  if (!file.existsSync()) {
    stderr.writeln('error: fixture not found at $fixturePath');
    exit(2);
  }

  final root = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final fixedComputedAt = root['fixed_computed_at'] as String?;
  if (fixedComputedAt == null || fixedComputedAt.isEmpty) {
    stderr.writeln('error: fixture missing "fixed_computed_at"');
    exit(2);
  }
  final products = (root['products'] as List?) ?? const [];
  if (products.isEmpty) {
    stderr.writeln('error: fixture has no "products"');
    exit(2);
  }

  final buffer = StringBuffer();
  _writeHeader(buffer);

  for (var i = 0; i < products.length; i++) {
    final product = products[i] as Map<String, dynamic>;
    final barcode = product['barcode'] as String;

    final tokens = ((product['ingredients_tokens'] as List?) ?? const [])
        .map((e) => e.toString())
        .toList(growable: false);
    final input = IngredientInput(tokens: tokens);
    final result = computeVerdict(input);

    final expectedVerdict = product['expected_verdict'] as String?;
    if (expectedVerdict != null && expectedVerdict != result.verdict.wireName) {
      stderr.writeln(
        'warning: $barcode expected $expectedVerdict but computed '
        '${result.verdict.wireName}',
      );
    }

    buffer.write(
      _renderInsert(
        product: product,
        verdictResult: result,
        computedAt: fixedComputedAt,
      ),
    );
    if (i < products.length - 1) buffer.writeln();
  }

  stdout.write(buffer.toString());
}

void _writeHeader(StringBuffer buffer) {
  buffer.writeln(
    '-- HappyCart MVP: seeded products. Auto-generated by '
    'tool/compute_verdicts.dart. Do NOT hand-edit.',
  );
  buffer.writeln('-- 룰 버전: $ruleVersion');
  buffer.writeln();
}

String _renderInsert({
  required Map<String, dynamic> product,
  required VerdictResult verdictResult,
  required String computedAt,
}) {
  final tokens = ((product['ingredients_tokens'] as List?) ?? const [])
      .map((e) => e.toString())
      .toList(growable: false);
  final ingredientsRaw = product['ingredients_raw'] as String? ?? '';

  return '''
insert into public.products (
  barcode, brand, name, size, category,
  ingredients_raw, ingredients_tokens,
  bad_ingredients_detected, good_ingredients_detected, verdict_reason_codes,
  verdict, rule_version, computed_at,
  source, source_url, source_checked_at, verified_status
) values (
  ${_q(product['barcode'])},
  ${_q(product['brand'])},
  ${_q(product['name'])},
  ${_q(product['size'])},
  ${_nq(product['category'])},
  ${_q(ingredientsRaw)},
  ${_textArray(tokens)},
  ${_textArray(verdictResult.badCanonicalKeys)},
  ${_textArray(verdictResult.goodCanonicalKeys)},
  ${_textArray(verdictResult.reasonCodes)},
  ${_q(verdictResult.verdict.wireName)}::public.verdict_enum,
  ${_q(ruleVersion)},
  ${_q(computedAt)}::timestamptz,
  ${_q(product['source'])},
  ${_nq(product['source_url'])},
  ${_q(product['source_checked_at'])}::timestamptz,
  ${_q(product['verified_status'] ?? 'verified')}::public.verified_status_enum
);
''';
}

/// SQL string literal — Postgres dollar-quoted to avoid escaping.
String _q(Object? value) {
  if (value == null) return 'null';
  final s = value.toString();
  return r"$hc$" + s + r"$hc$";
}

String _nq(Object? value) {
  if (value == null) return 'null';
  return _q(value);
}

String _textArray(List<String> items) {
  if (items.isEmpty) return "'{}'";
  final escaped = items.map((e) => '"${e.replaceAll('"', r'\"')}"').join(',');
  return r"'{" + escaped + r"}'";
}
