-- HappyCart MVP: seeded products. Auto-generated by tool/compute_verdicts.dart. Do NOT hand-edit.
-- 룰 버전: v1.0.0

insert into public.products (
  barcode, brand, name, size, category,
  ingredients_raw, ingredients_tokens,
  bad_ingredients_detected, good_ingredients_detected, verdict_reason_codes,
  verdict, rule_version, computed_at,
  source, source_url, source_checked_at, verified_status
) values (
  $hc$8801037088168$hc$,
  $hc$오레오$hc$,
  $hc$오레오 (오리지널)$hc$,
  $hc$100g (50g × 2봉지)$hc$,
  $hc$비스킷$hc$,
  $hc$밀가루(밀:미국산,호주산), 설탕, 분당(설탕,옥수수전분), 팜스테아린유(말레이시아산), 야자유, 가공유지(올리브유), 식물성유지(가공유지/팜스테아린유/에스테르화유지(팜스테아린유)), 해바라기유, 혼합제재(올리오레진로즈마리, 폴리글리세린축합리시놀레인산에스테르), 포도당, 옥수수전분, 팜유(말레이시아산) 67%, 정제소금, 코코아분말 33%, 내멸린드스 67%, 정제소금, 팽창제, 향료, 레시틴, 유당, 우유, 바닐린$hc$,
  '{"밀가루","설탕","분당","옥수수전분","팜스테아린유","야자유","가공유지","올리브유","식물성유지","에스테르화유지","해바라기유","올리오레진로즈마리","폴리글리세린축합리시놀레인산에스테르","포도당","팜유","정제소금","코코아분말","팽창제","향료","레시틴","유당","우유","바닐린"}',
  '{}',
  '{}',
  '{}',
  $hc$okay$hc$::public.verdict_enum,
  $hc$v1.0.0$hc$,
  $hc$2026-05-21T00:00:00Z$hc$::timestamptz,
  $hc$제조사 라벨 (동서식품)$hc$,
  $hc$http://www.dongsuh.co.kr$hc$,
  $hc$2026-05-21T00:00:00Z$hc$::timestamptz,
  $hc$verified$hc$::public.verified_status_enum
);

insert into public.products (
  barcode, brand, name, size, category,
  ingredients_raw, ingredients_tokens,
  bad_ingredients_detected, good_ingredients_detected, verdict_reason_codes,
  verdict, rule_version, computed_at,
  source, source_url, source_checked_at, verified_status
) values (
  $hc$8801047216438$hc$,
  $hc$동원$hc$,
  $hc$순참치액$hc$,
  $hc$500g$hc$,
  $hc$액상 조미료$hc$,
  $hc$가다랑어추출물 80% (혼합간장 1.5%, 정제수, 정백당, 정제소금, 가다랑어추출물 5.2%, 참치엑기스, 참치농축액), 참치엑기스 33%, 멸치엑기스 21.54%, 한식간장 4.8% (정제염, 정제소금, 표고버섯추출물), 정백당, 정제염, 양조식초, 표고버섯추출물, 토마토페이스트$hc$,
  '{"가다랑어추출물","혼합간장","정제수","정백당","정제소금","참치엑기스","참치농축액","멸치엑기스","한식간장","정제염","표고버섯추출물","양조식초","토마토페이스트"}',
  '{}',
  '{}',
  '{}',
  $hc$okay$hc$::public.verdict_enum,
  $hc$v1.0.0$hc$,
  $hc$2026-05-21T00:00:00Z$hc$::timestamptz,
  $hc$제조사 라벨 (동원F&B)$hc$,
  null,
  $hc$2026-05-21T00:00:00Z$hc$::timestamptz,
  $hc$verified$hc$::public.verified_status_enum
);

insert into public.products (
  barcode, brand, name, size, category,
  ingredients_raw, ingredients_tokens,
  bad_ingredients_detected, good_ingredients_detected, verdict_reason_codes,
  verdict, rule_version, computed_at,
  source, source_url, source_checked_at, verified_status
) values (
  $hc$8801062516735$hc$,
  $hc$롯데$hc$,
  $hc$칸쵸 초코$hc$,
  $hc$196g$hc$,
  $hc$초코 비스킷$hc$,
  $hc$밀가루, 정백당, 분당, 콘스타치, 식물성유지(가공유지/말레이시아산 팜유, 야자유), 고과당옥수수시럽(가공유지), 코코아매스 7%, 카라기난, 말토덱스트린, 콜라겐(말레이시아산), 정제소금, 식염, 팽창제, 산미료, 향료, 유화제(대두레시틴), 유당, 분유$hc$,
  '{"밀가루","정백당","분당","콘스타치","식물성유지","가공유지","팜유","야자유","고과당옥수수시럽","코코아매스","카라기난","말토덱스트린","콜라겐","정제소금","식염","팽창제","산미료","향료","유화제","대두레시틴","유당","분유"}',
  '{"carrageenan","hfcs","maltodextrin"}',
  '{}',
  '{"carrageenan","hfcs","maltodextrin"}',
  $hc$not_okay$hc$::public.verdict_enum,
  $hc$v1.0.0$hc$,
  $hc$2026-05-21T00:00:00Z$hc$::timestamptz,
  $hc$제조사 라벨 (롯데)$hc$,
  null,
  $hc$2026-05-21T00:00:00Z$hc$::timestamptz,
  $hc$verified$hc$::public.verified_status_enum
);

insert into public.products (
  barcode, brand, name, size, category,
  ingredients_raw, ingredients_tokens,
  bad_ingredients_detected, good_ingredients_detected, verdict_reason_codes,
  verdict, rule_version, computed_at,
  source, source_url, source_checked_at, verified_status
) values (
  $hc$8851103220480$hc$,
  $hc$Golden Field$hc$,
  $hc$Rice Bran Oil (현미유)$hc$,
  $hc$1L$hc$,
  $hc$식용유$hc$,
  $hc$현미유 100% (태국산). Gamma Oryzanol 10,000mg/L, Vitamin E 11.8mg α-TE/100mL.$hc$,
  '{"현미유","rice bran oil"}',
  '{}',
  '{}',
  '{}',
  $hc$okay$hc$::public.verdict_enum,
  $hc$v1.0.0$hc$,
  $hc$2026-05-21T00:00:00Z$hc$::timestamptz,
  $hc$제조사 라벨 (AGRO WELLNESS COMPANY LIMITED, 태국)$hc$,
  null,
  $hc$2026-05-21T00:00:00Z$hc$::timestamptz,
  $hc$verified$hc$::public.verified_status_enum
);

insert into public.products (
  barcode, brand, name, size, category,
  ingredients_raw, ingredients_tokens,
  bad_ingredients_detected, good_ingredients_detected, verdict_reason_codes,
  verdict, rule_version, computed_at,
  source, source_url, source_checked_at, verified_status
) values (
  $hc$8801052727523$hc$,
  $hc$청정원$hc$,
  $hc$곡물100 (이소말토 올리고당)$hc$,
  $hc$1.2kg$hc$,
  $hc$올리고당/시럽$hc$,
  $hc$옥수수전분 99.5%, 쌀 0.5%. 성분함량: 이소말토올리고당 20g 이상 (100g당/수분제외).$hc$,
  '{"옥수수전분","쌀","이소말토올리고당","올리고당"}',
  '{}',
  '{}',
  '{}',
  $hc$okay$hc$::public.verdict_enum,
  $hc$v1.0.0$hc$,
  $hc$2026-05-21T00:00:00Z$hc$::timestamptz,
  $hc$제조사 라벨 (대상 청정원)$hc$,
  $hc$https://www.daesang.com$hc$,
  $hc$2026-05-21T00:00:00Z$hc$::timestamptz,
  $hc$verified$hc$::public.verified_status_enum
);
