-- HappyCart MVP: seeded products. Auto-generated by tool/compute_verdicts.dart. Do NOT hand-edit.
-- 룰 버전: v1.0.0

insert into public.products (
  barcode, brand, name, size, category,
  ingredients_raw, ingredients_tokens,
  bad_ingredients_detected, good_ingredients_detected, verdict_reason_codes,
  verdict, rule_version, computed_at,
  source, source_url, source_checked_at, verified_status
) values (
  $hc$8801045312316$hc$,
  $hc$오뚜기$hc$,
  $hc$3분 쇠고기카레$hc$,
  $hc$200g$hc$,
  $hc$레토르트식품$hc$,
  $hc$정제수, 감자(미국산: 감자, 산도조절제), 양파퓨레(중국산), 쇠고기(뉴질랜드산), 혼합과일소스, 변성전분, 쇠고기브이용, 설탕, 식물성유지, 카레분, 유크림, 토마토페이스트, 쇠고기다시, 조미양념2, 마늘, 정제소금, 양파맛분말, 후추분, 고춧가루, 강황추출액, 덱스트린$hc$,
  '{"정제수","감자","산도조절제","양파퓨레","쇠고기","혼합과일소스","변성전분","쇠고기브이용","설탕","식물성유지","카레분","유크림","토마토페이스트","쇠고기다시","조미양념2","마늘","정제소금","양파맛분말","후추분","고춧가루","강황추출액","덱스트린"}',
  '{}',
  '{}',
  '{}',
  $hc$okay$hc$::public.verdict_enum,
  $hc$v1.0.0$hc$,
  $hc$2026-05-22T00:00:00Z$hc$::timestamptz,
  $hc$제조사 라벨 (오뚜기)$hc$,
  null,
  $hc$2026-05-22T00:00:00Z$hc$::timestamptz,
  $hc$verified$hc$::public.verified_status_enum
);
