-- HappyCart MVP: seeded products. Auto-generated by tool/compute_verdicts.dart. Do NOT hand-edit.
-- 룰 버전: v1.1.0

insert into public.products (
  barcode, brand, name, size, category,
  ingredients_raw, ingredients_tokens,
  bad_ingredients_detected, good_ingredients_detected, verdict_reason_codes,
  verdict, rule_version, computed_at,
  source, source_url, source_checked_at, verified_status
) values (
  $hc$8809990172030$hc$,
  $hc$웰코리아$hc$,
  $hc$사이다볼$hc$,
  $hc$9g$hc$,
  $hc$캔디류$hc$,
  $hc$백설탕, 포도당, 산도조절제(구연산), 합성착향료(사이다향), 청색1호, 혼합초록(황색4호, 청색1호)$hc$,
  '{"백설탕","포도당","산도조절제","구연산","합성착향료","사이다향","청색1호","혼합초록","황색4호"}',
  '{"artificial_flavors","blue_1","sugar"}',
  '{}',
  '{"artificial_color","opaque_flavor","refined_sugar"}',
  $hc$not_okay$hc$::public.verdict_enum,
  $hc$v1.1.0$hc$,
  $hc$2026-05-26T03:23:24Z$hc$::timestamptz,
  $hc$쿠팡 상세 페이지 (제조사 라벨 OCR)$hc$,
  $hc$https://www.coupang.com/vp/products/9527952283?itemId=28411065066&vendorItemId=95362241126$hc$,
  $hc$2026-05-26T03:18:11.482068+00:00$hc$::timestamptz,
  $hc$needs_review$hc$::public.verified_status_enum
);
